### ISSUE TITLE
Launch Stack failed

### ISSUE THREAD

**Issue by peterpham** [ks888/LambStatus#6]
I try to click a button launch stack but it failed. 
Here are some errors:

<pre>
...
21:49:36 UTC+1100	DELETE_IN_PROGRESS	AWS::IAM::Role	CognitoSMSCallerRole	
21:49:36 UTC+1100	DELETE_IN_PROGRESS	AWS::S3::BucketPolicy	StatusPageS3BucketPolicy	
21:49:29 UTC+1100	ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	StatusPage	The following resource(s) failed to create: [AdminPageFrontend, StatusPageDistribution, AdminPageDistribution, LambdaRoleInstanceProfile, StatusPageFrontend]. . Rollback requested by user.
21:49:27 UTC+1100	CREATE_FAILED	AWS::CloudFront::Distribution	StatusPageDistribution	Resource creation cancelled
21:49:27 UTC+1100	CREATE_FAILED	AWS::IAM::InstanceProfile	LambdaRoleInstanceProfile	Resource creation cancelled
21:49:27 UTC+1100	CREATE_FAILED	AWS::CloudFront::Distribution	AdminPageDistribution	Resource creation cancelled
21:49:27 UTC+1100	CREATE_FAILED	Custom::S3SyncObjects	AdminPageFrontend	Data returned must be an object
21:49:26 UTC+1100	CREATE_COMPLETE	AWS::DynamoDB::Table	ServiceComponentTable	
21:49:26 UTC+1100	CREATE_FAILED	Custom::S3SyncObjects	StatusPageFrontend	Data returned must be an object
21:49:26 UTC+1100	CREATE_COMPLETE	AWS::DynamoDB::Table	IncidentTable	
21:49:26 UTC+1100	CREATE_COMPLETE	AWS::DynamoDB::Table	IncidentUpdateTable	
21:49:23 UTC+1100	CREATE_COMPLETE	AWS::Lambda::Permission	GetComponentsLambdaInvokePermission	
...
</pre>

**Comment by ks888** [comment]
Thank you for trying!

I've just created the new stack, but I can't reproduce your issue.
It is nice if we have more detailed logs.

Can you see CloudWatch Logs?
I guess you have the LogGroup like `/aws/lambda/[Your CloudFormation Stack Name]-S3SyncObjects`,
and there will be more detailed logs.

**Comment by peterpham** [comment]
I saw 2 log streams in CloudWatch 

first log
<pre>
START RequestId: 98304cef-e159-11e6-a52d-dbfcfe3f4da1 Version: $LATEST
2017-01-23T10:49:21.075Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	received request
2017-01-23T10:49:21.075Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	source bucket name: lambstatus
2017-01-23T10:49:21.075Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	source key: admin-page/0.1.2
2017-01-23T10:49:21.075Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	destination bucket name: statuspage-adminpages3-1imst4q16ax6g
2017-01-23T10:49:25.416Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	Access Denied
2017-01-23T10:49:25.556Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	AccessDenied: Access Denied
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:538:35)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:668:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:670:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
2017-01-23T10:49:25.557Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	Response body:
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2017/01/23/[$LATEST]99a50b8fb0a1447097765def21276f72",
    "PhysicalResourceId": "2017/01/23/[$LATEST]99a50b8fb0a1447097765def21276f72",
    "StackId": "arn:aws:cloudformation:ap-southeast-2:219659643570:stack/StatusPage/85d64590-e159-11e6-bf3d-5081eaa770a1",
    "RequestId": "a054f646-0327-4ba1-83b5-ad825c930c75",
    "LogicalResourceId": "AdminPageFrontend",
    "Data": "Access Denied"
}

2017-01-23T10:49:25.925Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	Status code: 200
2017-01-23T10:49:25.925Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	Status message: OK
END RequestId: 98304cef-e159-11e6-a52d-dbfcfe3f4da1
REPORT RequestId: 98304cef-e159-11e6-a52d-dbfcfe3f4da1	Duration: 4858.77 ms	Billed Duration: 4900 ms Memory Size: 128 MB	Max Memory Used: 49 MB	
</pre>


second log
<pre>
START RequestId: 98a025fd-e159-11e6-a744-e1cac430344c Version: $LATEST
2017-01-23T10:49:21.715Z	98a025fd-e159-11e6-a744-e1cac430344c	received request
2017-01-23T10:49:21.715Z	98a025fd-e159-11e6-a744-e1cac430344c	source bucket name: lambstatus
2017-01-23T10:49:21.715Z	98a025fd-e159-11e6-a744-e1cac430344c	source key: status-page/0.1.2
2017-01-23T10:49:21.716Z	98a025fd-e159-11e6-a744-e1cac430344c	destination bucket name: statuspage-statuspages3-drli9rp6g9ej
2017-01-23T10:49:25.669Z	98a025fd-e159-11e6-a744-e1cac430344c	Access Denied
2017-01-23T10:49:25.715Z	98a025fd-e159-11e6-a744-e1cac430344c	AccessDenied: Access Denied
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:538:35)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:668:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:670:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
2017-01-23T10:49:25.716Z	98a025fd-e159-11e6-a744-e1cac430344c	Response body:
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2017/01/23/[$LATEST]71465758c1ca4cb186127411604e36cc",
    "PhysicalResourceId": "2017/01/23/[$LATEST]71465758c1ca4cb186127411604e36cc",
    "StackId": "arn:aws:cloudformation:ap-southeast-2:219659643570:stack/StatusPage/85d64590-e159-11e6-bf3d-5081eaa770a1",
    "RequestId": "29aa1414-6795-495b-8eed-d99fc2bc9d75",
    "LogicalResourceId": "StatusPageFrontend",
    "Data": "Access Denied"
}

2017-01-23T10:49:26.210Z	98a025fd-e159-11e6-a744-e1cac430344c	Status code: 200
2017-01-23T10:49:26.210Z	98a025fd-e159-11e6-a744-e1cac430344c	Status message: OK
END RequestId: 98a025fd-e159-11e6-a744-e1cac430344c
REPORT RequestId: 98a025fd-e159-11e6-a744-e1cac430344c	Duration: 4530.83 ms	Billed Duration: 4600 ms Memory Size: 128 MB	Max Memory Used: 48 MB	
START RequestId: a21ac165-e159-11e6-9642-0d0a3f3c5c70 Version: $LATEST
2017-01-23T10:49:37.054Z	a21ac165-e159-11e6-9642-0d0a3f3c5c70	Response body:
{
    "Status": "SUCCESS",
    "Reason": "See the details in CloudWatch Log Stream: 2017/01/23/[$LATEST]71465758c1ca4cb186127411604e36cc",
    "PhysicalResourceId": "2017/01/23/[$LATEST]71465758c1ca4cb186127411604e36cc",
    "StackId": "arn:aws:cloudformation:ap-southeast-2:219659643570:stack/StatusPage/85d64590-e159-11e6-bf3d-5081eaa770a1",
    "RequestId": "2b91732d-fe08-4f1b-99b7-b258be3d676a",
    "LogicalResourceId": "AdminPageFrontend"
}

2017-01-23T10:49:37.164Z	a21ac165-e159-11e6-9642-0d0a3f3c5c70	Status code: 200
2017-01-23T10:49:37.164Z	a21ac165-e159-11e6-9642-0d0a3f3c5c70	Status message: OK
END RequestId: a21ac165-e159-11e6-9642-0d0a3f3c5c70
REPORT RequestId: a21ac165-e159-11e6-9642-0d0a3f3c5c70	Duration: 121.10 ms	Billed Duration: 200 ms Memory Size: 128 MB	Max Memory Used: 48 MB	
START RequestId: a23a3035-e159-11e6-a52d-dbfcfe3f4da1 Version: $LATEST
2017-01-23T10:49:37.298Z	a23a3035-e159-11e6-a52d-dbfcfe3f4da1	Response body:
{
    "Status": "SUCCESS",
    "Reason": "See the details in CloudWatch Log Stream: 2017/01/23/[$LATEST]71465758c1ca4cb186127411604e36cc",
    "PhysicalResourceId": "2017/01/23/[$LATEST]71465758c1ca4cb186127411604e36cc",
    "StackId": "arn:aws:cloudformation:ap-southeast-2:219659643570:stack/StatusPage/85d64590-e159-11e6-bf3d-5081eaa770a1",
    "RequestId": "ed66e78f-9da1-4ba1-a197-0658b35d215a",
    "LogicalResourceId": "StatusPageFrontend"
}

2017-01-23T10:49:37.385Z	a23a3035-e159-11e6-a52d-dbfcfe3f4da1	Status code: 200
2017-01-23T10:49:37.385Z	a23a3035-e159-11e6-a52d-dbfcfe3f4da1	Status message: OK
END RequestId: a23a3035-e159-11e6-a52d-dbfcfe3f4da1
REPORT RequestId: a23a3035-e159-11e6-a52d-dbfcfe3f4da1	Duration: 87.42 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 48 MB	
</pre>

**Comment by ks888** [comment]
Thank you! I've just reproduced the issue you reported. I'm going to fix this within a few days.

**Comment by ks888** [comment]
I fixed the issue, and released the new version v0.1.3. Click the 'Launch Stack' button again, and it will work out!

**Comment by peterpham** [comment]
I tried it again
This time, there is a new error

> 2 validation errors detected: Value at 'username' failed to satisfy constraint: Member must have length greater than or equal to 1; Value at 'username' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+

**/aws/lambda/StatusPage-CognitoCreateUser**
<pre>
START RequestId: 2d756f92-e456-11e6-9934-bb76cf0dbf88 Version: $LATEST
2017-01-27T06:02:28.053Z	2d756f92-e456-11e6-9934-bb76cf0dbf88	2 validation errors detected: Value at 'username' failed to satisfy constraint: Member must have length greater than or equal to 1; Value at 'username' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+
2017-01-27T06:02:28.111Z	2d756f92-e456-11e6-9934-bb76cf0dbf88	InvalidParameterException: 2 validation errors detected: Value at 'username' failed to satisfy constraint: Member must have length greater than or equal to 1; Value at 'username' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:43:27)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:668:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:670:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
2017-01-27T06:02:28.112Z	2d756f92-e456-11e6-9934-bb76cf0dbf88	Response body:
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2017/01/27/[$LATEST]d00faefe72f1429a837b540789e82415",
    "PhysicalResourceId": "2017/01/27/[$LATEST]d00faefe72f1429a837b540789e82415",
    "StackId": "arn:aws:cloudformation:ap-southeast-2:219659643570:stack/StatusPage/9796c330-e452-11e6-89bc-5081ec3a9811",
    "RequestId": "67eee1ea-8c98-49c1-a7fc-e8b11b68f0da",
    "LogicalResourceId": "CognitoInitialUser"
}

2017-01-27T06:02:28.317Z	2d756f92-e456-11e6-9934-bb76cf0dbf88	Status code: 200
2017-01-27T06:02:28.317Z	2d756f92-e456-11e6-9934-bb76cf0dbf88	Status message: OK
END RequestId: 2d756f92-e456-11e6-9934-bb76cf0dbf88
REPORT RequestId: 2d756f92-e456-11e6-9934-bb76cf0dbf88	Duration: 1547.62 ms	Billed Duration: 1600 ms Memory Size: 128 MB	Max Memory Used: 26 MB	
START RequestId: 36609b5d-e456-11e6-923f-e5cca52dd804 Version: $LATEST
2017-01-27T06:02:41.290Z	36609b5d-e456-11e6-923f-e5cca52dd804	Response body:
{
    "Status": "SUCCESS",
    "Reason": "See the details in CloudWatch Log Stream: 2017/01/27/[$LATEST]d00faefe72f1429a837b540789e82415",
    "PhysicalResourceId": "2017/01/27/[$LATEST]d00faefe72f1429a837b540789e82415",
    "StackId": "arn:aws:cloudformation:ap-southeast-2:219659643570:stack/StatusPage/9796c330-e452-11e6-89bc-5081ec3a9811",
    "RequestId": "72140a66-26d2-45c4-a8a8-0637b8a5b512",
    "LogicalResourceId": "CognitoInitialUser"
}

2017-01-27T06:02:41.361Z	36609b5d-e456-11e6-923f-e5cca52dd804	Status code: 200
2017-01-27T06:02:41.362Z	36609b5d-e456-11e6-923f-e5cca52dd804	Status message: OK
END RequestId: 36609b5d-e456-11e6-923f-e5cca52dd804
REPORT RequestId: 36609b5d-e456-11e6-923f-e5cca52dd804	Duration: 79.56 ms	Billed Duration: 100 ms Memory Size: 128 MB	Max Memory Used: 26 MB	
</pre>


**/aws/lambda/StatusPage-S3SyncObjects**
<pre>
START RequestId: 98304cef-e159-11e6-a52d-dbfcfe3f4da1 Version: $LATEST
2017-01-23T10:49:21.075Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	received request
2017-01-23T10:49:21.075Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	source bucket name: lambstatus
2017-01-23T10:49:21.075Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	source key: admin-page/0.1.2
2017-01-23T10:49:21.075Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	destination bucket name: statuspage-adminpages3-1imst4q16ax6g
2017-01-23T10:49:25.416Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	Access Denied
2017-01-23T10:49:25.556Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	AccessDenied: Access Denied
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:538:35)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:668:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:670:12)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
2017-01-23T10:49:25.557Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	Response body:
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2017/01/23/[$LATEST]99a50b8fb0a1447097765def21276f72",
    "PhysicalResourceId": "2017/01/23/[$LATEST]99a50b8fb0a1447097765def21276f72",
    "StackId": "arn:aws:cloudformation:ap-southeast-2:219659643570:stack/StatusPage/85d64590-e159-11e6-bf3d-5081eaa770a1",
    "RequestId": "a054f646-0327-4ba1-83b5-ad825c930c75",
    "LogicalResourceId": "AdminPageFrontend",
    "Data": "Access Denied"
}

2017-01-23T10:49:25.925Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	Status code: 200
2017-01-23T10:49:25.925Z	98304cef-e159-11e6-a52d-dbfcfe3f4da1	Status message: OK
END RequestId: 98304cef-e159-11e6-a52d-dbfcfe3f4da1
REPORT RequestId: 98304cef-e159-11e6-a52d-dbfcfe3f4da1	Duration: 4858.77 ms	Billed Duration: 4900 ms Memory Size: 128 MB	Max Memory Used: 49 MB	
</pre>

**Comment by ks888** [comment]
Oh, I guess you don't enter `UserEmail` and `UserName` parameters on creating the stack.

`UserName` can be anything unless empty, but `UserEmail` should be the valid email address, since the initial password will be sent to the email address.

<img width="918" alt="2017-01-28 12 12 34" src="https://cloud.githubusercontent.com/assets/8448120/22393847/397278d8-e553-11e6-93ba-616a43d0e0f8.png">

**Comment by ks888** [comment]
https://github.com/ks888/LambStatus/issues/7 will improve this point.

**Comment by peterpham** [comment]
You were right. I didn't enter a username and email. 
After trying again, it is now working.
Thank you.

**Comment by nwoodthorpe-test1** [comment]
ו̸̙͓̙̝̯̥̗̩̟͈̗̠͐̏ͯ̒̈́̌̿̍̊̿͊̓ͯ̽̈ה̌̿ͩ̽̑͗ͮ̐͞҉̹͈̭̞̫̘͇̱̦̦͍̱́ע̭͈̱̣̤͕͙̹̙̮̲̝ͪͤ͐̿͂ͥ͌ͦͮͪ̕͢͠ב̨͍̹̠̜͙͙̺̝̬̙̯̹͚͊̈̉͌ͥ̈́̇͜ר̵̲̭̘̭̌́̐̚י̨̹̹͔̫̺̳͙̒ͣ̉̾̀̾͗͂̑͐̈̄̃̏̃̃͂͘͜͟ת̸̴̶̨͈̤̘͎̘̫̪̺̱̅͒̓̋͐ͣ ̧̻̤̮̠͛̍ͣ͊́̕͡͡ה̵̸̶̷̧̣͕̘̪̱̘̗̯͍̮͗̑ͫ̓ͧ̿̀ͪ͛̎ͦ̈́ͩו̉̆̈́͋̄ͫ̀̄͋̂͑̽̓̋͐̎̕͘҉̴͎̮̝̥̼͈̝̠̹̤͓̭̗́ק͔̹̰̺͙̔̓͗ͣͦͨ̔̒̇̈́ͪ̅̏͡͡͡͞ל̴̞̳̩̞̻̼͚̜͔͉̮̺̜̩͚̓ͮ̀̌̈́͘ד̴͉͔̗̬͔̑̉̏͌ͯ͜͟ͅͅ ̸̴̺̺͕̗̦̙͇̟̽͐̔̔ͦ͊ͯ̑ͧͪͥ͆ש͗̈ͬͭ̐͏̢̞̻͚̗̖̖̮͔͓͍͖͙̹̗͈͍̠̳͝נ̨̡̰̜͖̰͙̪̺ͫͪ̑̍̎ͯ̿ͣ͒ͥ͊̌͂ͭ̃̐͌̚͜י̵̵̼̙̺͚͓͍̲̝̹̥͍͉̦̻ͥͭ͗ͪ͛̃̄̀͞ו̧̳̙͙̃ͬͭ̓̉̊̾̃ͥ̏͛ͪ̆̊̌͑̽̍͡ה̴̵̨̥͓͖̟͎̞̖ͭ͗͋ͥ̏ͥͮ̆ͭ͝ע̶̶̡̨͉͉̯̲͖͔̠̞͚̺͔͇̪̤̺̻͇̈̈́̋͒͋ͫͦ́̒ͭ͛̽̈̋̓͘ב̛͌̇͋ͪ̽ͮ̉̀ͫ̄̓̋͗̐̆ͣ̃͝͠͠͏̭͎͙̳̫̹̲͖̰̹͔̜̟̭͕̪ר͉̼̘̯̭̙͉̭̬̫̞̗̗̭̯̒ͧͫ͊̾͋̅͗͑̀ͨ͡͠י̡̩̩̟̮̱̍̎̔̔͆̄̅̔̿̒͛͊̉̇̃̆̋̚͘͞ת̽̑͂̊ͭ̀ͦͮ̀ͯ͏̡̫̰͈̭̳͕̣͚̕ ̶̡̦͈̦͎̤̭̤̣̥̋ͥ̽ͬ̿͐̂̉̉͐̔ͪ̇ͧͦ̈́̀ה͑ͦ͐ͤ̑̄͑̓͒ͧͧ͠҉̬͍̣̱̯̬ו̢͕̲̼̠̘̊ͭ́̾̏̈́͘͠͠͡ק̷͍̥̼̳̖̥̦̻̞̦̺̤̠̥͚̥̓̂̐ͨ̚͘͟͠ל̧ͣ͊͆ͦ̓͂ͥ͋͌̄́̓̇̔̆ͦ̊҉̨̮̰̩͙̫̟̰̖̝̺͜ד̷̵̅̿̾͑̊̉͊̈́͞͏̵̰̬̯͍͈͕͎͕̥̥̭ͅ ̜͔̰̭̹͎̪̭͑ͨ̔̈ͨͧ̎̇̋̄ͬ͆̚͢͠ͅש̟̮̗͈̤̜̩͇͓̩̬̈́͒̌̔̔̆̀̚̕͜͝נ̵̴̴͕̳͖̱̪͛ͣͫ̎ͫ̊͒י̵̡͙̯̫͓̹̼̥̥̹̺ͣͭͭͣͥ̂̀͜͞ו̷̨̛̲̹̥͎̗͉͉̘̙̳̬̺̆ͯͣͯ͊̓̈́̑͗̒̅̚ͅה̸̧̘͖͔̻̬ͤ̀͆͂͐ͯ͋͟͠͝ע̢̛͓̱̳͓̐̅̐ͦ͗̓̔͊͂́ͪ̽̾ͪ̃ͮͬ́͘͝ב̢̠̮̦̭̖̤̦̳̲͈͓̈ͯ̄̆ͦ̿ͨ̍̌ͦͬ͐͑ͪ͑ͥ̏̇͜ר̶̸̧̹͇̖̭͖̪̳͈͉̩̤͈̌̑̏̌͋̉̀͝ͅי̷̡̢̧̤̱̗̹͉̭͈̲̳̦͇̰̳͓͚̙̰́̽ͣ̍ͭͧ̍ͦ̈͗̅̽͊̆ͬ̀ͫ̕ת̒̀ͧ̑̔̌̓ͫͩ̚҉̸̡̱̞̤̝̗͈̰ ̷͇̝̤͚̥͈̩͔͔̬͙̱͚͙͓͖̺͈̄͌͂̒́͛ͪ̀́̕͟ה̸̖̗̺̳̝͉̠̥̳͍̮̣͎͇͇͎͈̱͚͑̋ͫ̈ͩ̍̃ͨ̆͆ͣ̀͟͝ו̢̖̺̬̙̺̲͙͇̮̾͆ͨ̅̉̅́ק̡̢̤̬̰̪̬ͮͮ̿̄͂͛ͤͦ̏̃̂ͩ͘͝ל̵̨͖̝͚̙̙̼͔̤̥ͨ̅͌͗̅͂̇͘͞ד̧͇͇̘̘̙̯̲̩̘̠̘͉̣̘̞̞̺̻͊́ͦ͌̐ͤ͗̀̾͂̀̾̑ͨ͞ͅ ̬̦̹̠͖̥̠̰̙̝̼̫̺͕̝̗͉ͫͥ́͗͐ͮ͌̔ͦ̅̂͡͠ש̶̠͉͙̤͎͉͖͕̙̦͙̺͔̘ͧ̍̇ͨ̋ͭ͛ͬ̾ͬ͢נ̡͇̩̫̻̩͍̰̻̼͈͍̲̥̹̖̄͒̓ͭ̀͟ͅי̡̢̝͚̘̝͚͔̹̖̪̙̖͍̎̌͒̂ͧͭ̊̂͊͘͝ͅו̸̴̮̥̜̮̦̟͔͕̰̗̻͓̮̙̗̀ͬ̓ͦͬ̽̿̾ͫ͐̅ͩ̑̒̑̒̏̚͟͢͠ה̷̛̟͖̤̗̮͓̮͈̺̜̺̱̂͊ͨ͒̂̃ͣͫ́͂̔́ͭ͑̓̈̚ע̢̤̫̟̻͎̤ͥͦ͐͆ͯ̾̉̄͜ב̻̮̟̦̱̯̘͉̰̹͖̜̞ͣ͗̽͆͑ͬͬ̓̄̋͌̅̊́̈͋̚̕͞ר̉̊̉̅́ͫ̈́͂̐ͮ̇̾͛ͦ̓̊͏҉̻̰̪͎͔̹̗̝̰̫̣̥̱̟̮̩͢͠י̸̢̩̳̼̫͈̳̫͖̘̯̳͖̫̣̺̰ͮ̎̈́ͬ̓̌̇ͦͦͫ͋̓̄̕͘ͅͅͅתͯ̔̊̒ͥͮ̽ͯ̀́̿̂͊̀̃̐ͦ̚͏̴̟̭̼̞̰̭̘̲̥̙͖̗̩̭͉̪̪͕͖͘͠ ̶̨̮͉̮̼̦̩̱͎͙̳̙͈͚̝̜͖̻ͧ̑̑͐̃ͥͩͬ̄ה̡̧͈͉͈̰͉͈̳̣̫̻̰̝͖͐ͦͬͩ̆̆ͣ̓̾̚̚͝ͅו͚̫͈͖͕̫͚͖͙̺̎̿ͩ̔̂̿̂̒ͩ̋͒̀ק̠͍͖̬͕̫͎͇̘̯̬͎̗̥̞͎͎̺ͯͩ͋̅̊͗́̍͋̀̕̕͡͝ל̩̳̤̼̘̱͕͓͈͓̓͂͂̒ͫ͌ͩ̆̋̇̃̓̀́̚͞ד̴̵͚̗͇̲̝̠̦̓͂̌͐̎ͯ̉̏̉ͫ̆̉̈̓̇͡ ̴̺̻̪̹̣̰̆͑̌̆̓ͬ͗ͧ̉̎̀̇̋ͮ̌̽̅͟͞ͅש̃ͤ͊̆̑̆̌̆ͨ̾ͤ̌̽̿̊͏̖̯̘̥̭̞̠͕͍̻̬̠̜͚̬̫̯̤͘נ̶̢̼̜͓̭͓̤͇̝̲̰̬̙̳͆͒ͩ̇ͮͅי̵̗͉̫̝̝̘̱̟̿͐́̒̌͒̃̄ͧ̈ͫ͒̋̂̓͌͊̈̀͘̕̕ו̶̡̣̲̺̭̱͖̻̙̲̱̱̹ͥ͋̍̓͑ͩ̀̏̐ͭ͋̅ͥ̌ͧ̊̚̚ה̡̨̳̰̖̮͍̟̐͋̓͊̾̍ͥ́ͅע̵̖͔̱̻̼̞̻͉̦ͧ̉̀̀ͣ̊͌̈ͥ́̑͊̊͆̑͗͗͘͡ͅב̴̴̼̖͚̹̯̤̙̹͚͈̽͒ͦ̎̐̓̋ͤͮ͊͌̿͂͆̂̓͘͡ͅר͍͚̺̩̱̩̠͇͓̜ͥ̐̍̐͘י̶̲̱̣̟̳͔͚̙͙̮ͨ̈̌̎̂͒̍̓ͥͮ̾ת̷͉̮͍̥͍̰̮ͣ͊ͪ̿̾̽͊̄ͣ̇͘͠ ̴̞̼̟̤̹̙̻͚͚͚̲̭̱͚͛̌́̐ͫ̑̄ͧ̍͟͢ͅͅה̸̛̞͉͍̼̳̝̼̪̦̅̋ͯ͌̆ͦͥ̐ͥ͑ͪͦ̈ͩ̇ͦ͊̚͘͠͞ו̧̧̛̛̜̜͙̯̤͇͉͖͛͒͑͠ק̽ͬ̍̽ͨ͊͌ͦ͏͏͇̟̱͍̱̝̬̖̟͈̖ͅ
